name: Build and Publish Docker Image
on:
  push:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to GitHub Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Build and push Docker image
      run: |
        docker build -t docker.pkg.github.com/${{ github.repository }}/my-container:${{ github.sha }} .
        docker push docker.pkg.github.com/${{ github.repository }}/my-container:${{ github.sha }}

